<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AdventurersGuild.Database.Abstract\AdventurersGuild.Database.Abstract.csproj" />
    <ProjectReference Include="..\AdventurersGuild.Models\AdventurersGuild.Models.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
