// <auto-generated />
using System;
using AdventurersGuild.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdventurersGuild.Database.Migrations
{
    [DbContext(typeof(GuildContext))]
    partial class GuildContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("AdventurersGuild.Models.Adventurer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adventurers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Торин Железнорукий",
                            Rank = "B"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Элара Быстрый Лист",
                            Rank = "C"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Магнус Пепельный",
                            Rank = "D"
                        });
                });

            modelBuilder.Entity("AdventurersGuild.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdventurerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Reward")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdventurerId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Хозяин таверны жалуется на нашествие крыс.",
                            Reward = 50m,
                            Status = 2,
                            Title = "Убить крыс в подвале таверны"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Кошка пропала три дня назад в районе рынка.",
                            Reward = 30m,
                            Status = 2,
                            Title = "Найти пропавшую кошку"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Срочное письмо для командира гарнизона.",
                            Reward = 80m,
                            Status = 2,
                            Title = "Доставить письмо в Восточный форт"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Сопровождение каравана до перевала Серых Камней.",
                            Reward = 300m,
                            Status = 2,
                            Title = "Охрана купеческого каравана"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Мельник подозревает поджог. Найти виновного.",
                            Reward = 150m,
                            Status = 2,
                            Title = "Расследование пожара на мельнице"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Банда орудует на дороге к северу от города.",
                            Reward = 400m,
                            Status = 1,
                            Title = "Зачистка бандитского лагеря"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Маг Ортан не вернулся из экспедиции в Тёмный лес две недели назад.",
                            Reward = 500m,
                            Status = 1,
                            Title = "Поиск пропавшего мага"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Травнице нужны корни лунного цветка с болот.",
                            Reward = 120m,
                            Status = 1,
                            Title = "Сбор лечебных трав"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Мост обрушился, нужны плотники и охрана.",
                            Reward = 200m,
                            Status = 1,
                            Title = "Починить мост через реку Грай"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Информатор скрывается в портовом квартале. Доставить живым.",
                            Reward = 350m,
                            Status = 1,
                            Title = "Допросить информатора"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Гарпии нападают на пастбища к западу от города.",
                            Reward = 600m,
                            Status = 0,
                            Title = "Уничтожить гнездо гарпий"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Старинный медальон был утерян в руинах древней крепости.",
                            Reward = 800m,
                            Status = 0,
                            Title = "Найти артефакт в руинах Калдара"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Требуется охрана на трёхдневную городскую ярмарку.",
                            Reward = 250m,
                            Status = 0,
                            Title = "Охрана ярмарки"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Жители деревни Пустошь видели мертвецов у кладбища.",
                            Reward = 450m,
                            Status = 0,
                            Title = "Расследовать слухи о некроманте"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Солдат бежал с поста с казёнными деньгами.",
                            Reward = 380m,
                            Status = 0,
                            Title = "Поймать дезертира"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Нужно выяснить, что происходит в перевале Туманного хребта.",
                            Reward = 320m,
                            Status = 0,
                            Title = "Разведка в горном перевале"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Культисты захватили паломников в старом храме.",
                            Reward = 700m,
                            Status = 0,
                            Title = "Освободить заложников"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Алтарь тёмного бога найден в катакомбах под городом.",
                            Reward = 900m,
                            Status = 0,
                            Title = "Уничтожить проклятый алтарь"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Чертежи новой крепости похищены из архива герцога.",
                            Reward = 550m,
                            Status = 0,
                            Title = "Найти украденные чертежи"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Дракон Вермитар терроризирует деревни уже полгода.",
                            Reward = 5000m,
                            Status = 0,
                            Title = "Убить дракона в Пепельных горах"
                        });
                });

            modelBuilder.Entity("AdventurersGuild.Models.Quest", b =>
                {
                    b.HasOne("AdventurersGuild.Models.Adventurer", "Adventurer")
                        .WithMany("Quests")
                        .HasForeignKey("AdventurerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Adventurer");
                });

            modelBuilder.Entity("AdventurersGuild.Models.Adventurer", b =>
                {
                    b.Navigation("Quests");
                });
#pragma warning restore 612, 618
        }
    }
}
